---
title: "Awesome Stuff"
---

## Cyber, Security, and Privacy

### News Feeds

- [Krebs on Security](https://krebsonsecurity.com/) [<i class="bi bi-rss"></i>](https://krebsonsecurity.com/feed/)
- [Bleeping Computer](https://www.bleepingcomputer.com/) [<i class="bi bi-rss"></i>](https://www.bleepingcomputer.com/feed/security/)
- [Bruce Schneier](https://www.schneier.com/) [<i class="bi bi-rss"></i>](https://www.schneier.com/feed/)
- [Troy Hunt](https://www.troyhunt.com/) [<i class="bi bi-rss"></i>](https://www.troyhunt.com/rss/)
- [Hacker News](https://news.ycombinator.com/) - [Quality News](https://news.social-protocols.org/)
- [Military Times Early Bird Briefing](https://ec.militarytimes.com/ebb/)


### Learning Resources

- [Privacy Guides](https://www.privacyguides.org/) [<i class="bi bi-rss"></i>](https://www.privacyguides.org/articles/feed_rss_created.xml) - privacy-focused tools and recommendations
    - [PrivacyTools](https://www.privacytools.io/)
- [MITRE ATT&CK](https://attack.mitre.org/)
- [Building a home lab](https://aj-labz.gitbook.io/aj-labz)
- [USASOC Smart Cards](https://www.soc.mil/IdM/publications/IdMpubs.html)
- [Terms of Service; Didn't Read](https://tosdr.org/)
- [Kali](https://www.kali.org/) - Linux distribution for penetration testing and security auditing with a massive collection of tools


###  Tracker, Ad-blockers, Malware Protection

- [Cloudflare for Families](https://blog.cloudflare.com/introducing-1-1-1-1-for-families/) - DNS-based malware protection
- [Pi-hole](https://pi-hole.net/) - network-wide DNS-based ad blocker
- [pfSense](https://www.pfsense.org/) - open-source firewall
- [NextDNS](https://nextdns.io/) - DNS-based tracker blocker


###  Self-hosted services, tools, networks

- [Tailscale](https://tailscale.com/) - mesh networking (personal VPN) for your devices
- [Syncthing](https://syncthing.net/) - file synchronization across devices
- [Nextcloud](https://nextcloud.com/) - self-hosted cloud storage, calendar, contacts, [RSS feed reader](https://en.wikipedia.org/wiki/RSS)
- [Gitea](https://gitea.io/) - self-hosted Git service, replacement for GitHub
- [Bitwarden](https://bitwarden.com/) - self-hosted password manager
- [Jitsi](https://jitsi.org/) - self-hosted video conferencing
- [Mattermost](https://mattermost.com/) - self-hosted Slack alternative


### Messaging, Email, Communication

- [Signal Messenger](https://signal.org/) - non-profit, encrypted messaging, voice, and video calls
- [ProtonMail](https://protonmail.com/) - encrypted email
- [Element](https://element.io/) - encrypted chat, video, and voice calls based on [Matrix](https://matrix.org/) protocol; can run your own server
- [PGP Encryption](https://www.privacytools.io/encryption-tools/pgp/gpg/)


### Android Tools and Resources

- [F-Droid](https://f-droid.org/) - open-source Android app store for [free](https://en.wikipedia.org/wiki/Free_software) and [open-source](https://en.wikipedia.org/wiki/Free_and_open-source_software) apps
- [LineageOS](https://lineageos.org/) - open-source Android OS that supports many devices
- [GrapheneOS](https://grapheneos.org/) - privacy-focused Android OS for Pixel devices
- [CalyxOS](https://calyxos.org/) - privacy-focused Android OS
- [/e/OS](https://e.foundation/e-os/) - deGoogled Android OS


### News, Articles, Documentaries

- [Flipper Zero (2023)](https://www.youtube.com/embed/nLIp4wd0oXs)
    - [Meanwhile, in Canada... (2024)](https://arstechnica.com/security/2024/02/canada-vows-to-ban-flipper-zero-device-in-crackdown-on-car-theft/)
- [Inside the "3 Billion People" National Public Data Breach (2024)](https://www.troyhunt.com/inside-the-3-billion-people-national-public-data-breach/)
- [The Global Surveillance Free-for-All in Mobile Ad Data (2024)](https://krebsonsecurity.com/2024/10/the-global-surveillance-free-for-all-in-mobile-ad-data/)
- [The Social Dilemma (2020)](https://www.netflix.com/title/81254224) - documentary on social media
- [The Great Hack (2019)](https://www.netflix.com/title/80117542) - documentary on Cambridge Analytica scandal


### What can you do?

- [haveibeenpwned.com](https://haveibeenpwned.com/) - subscribe to breach notifications
- [Mozilla Monitor](https://monitor.mozilla.org/) - find and fix data exposures
- [Firefox](https://www.mozilla.org/en-US/firefox/) - privacy-focused browser
- [DuckDuckGo](https://duckduckgo.com/privacy) - privacy-focused search engine
- [Cover Your Tracks](https://coveryourtracks.eff.org/) - browser fingerprinting test
- [NextDNS](https://nextdns.io/) - DNS-based tracker blocker
    - or self-host [Pi-hole](https://pi-hole.net/)
- [Consumer Reports: Privacy and Security](https://www.consumerreports.org/digital-security-privacy/)
- [Surveillance Self-Defense](https://ssd.eff.org/)
- [Data Removal Guide: inteltechniques.com](https://inteltechniques.com/workbook.html)


## Computing and Technology

- [Hackaday](https://hackaday.com/) [<i class="bi bi-rss"></i>](https://hackaday.com/feed/)
- [Hide and Seek!](https://www.youtube.com/embed/Lu56xVlZ40M)
- [Can ChatGPT be wrong?](https://chatgpt.com/share/a329b032-7e1d-4568-be40-9227de866a8b)
- [What is Python](https://www.youtube.com/embed/x7X9w_GIm1s)
- [arrr](https://arrr.readthedocs.io/) - Pirate module for Python
- [Where really is the Internet?](https://www.youtube.com/embed/Ve810FHZ1CQ)
- [Seating chart generator](https://gist.github.com/aadityabhatia/86077fea4ccd353bfb017df733a70d19)
- [Vortex Cannon vs Drone](https://www.youtube.com/embed/SrGENEXocJU)
- Algorithms
    - [The Better Boarding Method Airlines Won't Use](https://www.youtube.com/embed/oAHbLRjF0vo)
    - [PB&J Sandwich](https://www.youtube.com/embed/FN2RM-CHkuI)


### Programming References

- [DevDocs.io](https://devdocs.io/)
- [Programming Books for Professionals](https://goalkicker.com/)
- [Official Python Documentation](https://docs.python.org/)
- [Programming References on Canvas](https://westpoint.instructure.com/courses/7068/pages/programming-references)
- [How to Python in VS Code](https://py-vscode.readthedocs.io/)
- [Hour of Python](https://hourofpython.com/)
- [Khan Academy: Intro to Python Fundamentals](https://www.khanacademy.org/computing/intro-to-python-fundamentals)


### Developer Tools

- [Marimo](https://marimo.app/) reactive notebook for Python
- [Visual Studio Code](https://code.visualstudio.com/) - development environment for grown-ups
- [CircuitPython Code Editor](https://code.circuitpython.org/) - IDE to work with microcontrollers like [Circuit Playground Bluefruit](https://www.adafruit.com/product/4333)
- [diff Check](https://diffcheck.io/) - compare text side-by-side; great for comparing expected and actual output
- [Pyodide](https://pyodide.org/en/stable/console.html) - in-browser REPL
- [Python Tutor](https://pythontutor.com/python-compiler.html) - step through code execution, line-by-line
- [Black Code Formatter](https://black.vercel.app/) - format Python code following [PEP 8 Style Guide](https://peps.python.org/pep-0008/)
- [Thonny](https://thonny.org/) - Python development environment for beginners


### Project Ideas and Resources

- [Make It Yourself](https://makeityourself.org/) - A Beautifully Illustrated Guide to Making
- [Hackaday](https://hackaday.com/) [<i class="bi bi-rss"></i>](https://hackaday.com/feed/)
- [Hacker News: Show](https://news.ycombinator.com/show)
- [Example Projects [Canvas]](https://westpoint.instructure.com/courses/7068/files/1911864/download)
- [Text-based adventure game [zybook]](https://learn.zybooks.com/zybook/WESTPOINTCY105Fall2024/chapter/17/section/1)
- [zork-py](https://github.com/iamjawa/zork-py) library for Python
- [Kaggle Data Science Notebook](https://www.kaggle.com/code/ldfreeman3/a-data-science-framework-to-achieve-99-accuracy#Step-4:-Perform-Exploratory-Analysis-with-Statistics)
- Circuit Playground Bluefruit: Puzzle Box, Escape Room, etc.
    - [Fruit Piano](https://www.youtube.com/embed/UibfAZb1Xwo)
- [tldraw makereal](https://makereal.tldraw.com/) - bring your application sketches to life! - [watch demo](https://www.youtube.com/embed/Ov2N2fd6Xm4)
- Develop applications that use AI at runtime-
    - [OpenAI API](https://platform.openai.com/) - message them for API credits as a student researcher
    - [Anthropic API](https://console.anthropic.com/) - free limited API access
    - [Streamlit](https://streamlit.io/) - hosting platform to turn data scripts into shareable web apps using Python
- [Deepnote](https://deepnote.com/) - interactive web applications in Python
- [Marimo](https://marimo.io/) - interactive web applications in Python
- [GitHub pages](https://pages.github.com/) - host your websites and JavaScript applications for free
- [Using Bluetooth (BLE) with Circuit Playground Bluefruit](https://github.com/adafruit/Adafruit_CircuitPython_BLE_Radio)
- [Multi-tasking with CircuitPython](https://learn.adafruit.com/multi-tasking-with-circuitpython/overview)


## Learning and Productivity

- [YouTube: Bloom’s Taxonomy: Structuring The Learning Journey](https://www.youtube.com/embed/ayefSTAnCR8)
    - Ref: [Armstrong, P. (2010). Bloom’s Taxonomy. Vanderbilt University Center for Teaching.](https://cft.vanderbilt.edu/guides-sub-pages/blooms-taxonomy/)
- [Pareto Principle [The 80/20 Rule Explained]](https://www.youtube.com/embed/lsGwqk_agcQ)
- [Growth Mindset](https://www.youtube.com/embed/KUWn_TJTrnU)
- Why take good notes?
    - [Active learning](https://www.youtube.com/embed/xxVxgQJwV7w)
    - Memory retention
    - Future reference
- How to take good notes?
    - [Logseq](https://logseq.com/) or [Obsidian](https://obsidian.md/) - journaling, linking, knowledge management
    - OneNote
    - [Zettelkasten](https://zettelkasten.de/) [<i class="bi bi-rss"></i>](https://zettelkasten.de/feed.atom) - integrated thinking method!
        - [Zettelkasten Explained](https://www.youtube.com/embed/GpV47rUYk8I)
- The need for sleep
    - [Your Brain On Sleep Deprivation](https://www.youtube.com/embed/lvKrDsreUgM)
    - [What would happen if you didn’t sleep?](https://www.youtube.com/embed/dqONk48l5vY)
    - [How Sleep Affects Your Brain](https://www.youtube.com/embed/IzQ2siryQrM)
- [About, Ideas, Now](https://aboutideasnow.com/)

## Awesome Podcasts

- [Inside West Point: Ideas That Impact](https://inside-west-point-ideas-that-impact.captivate.fm/) [<i class="bi bi-rss"></i>](https://feeds.captivate.fm/inside-west-point-ideas-that-impact/)
- [Lex Fridman](https://lexfridman.com/podcast) [<i class="bi bi-rss"></i>](https://lexfridman.com/feed/podcast/)
- [No Such Podcast](https://sites.libsyn.com/542957) [<i class="bi bi-rss"></i>](https://feeds.libsyn.com/542957/rss)
- [Irregular Warfare Podcast](https://irregularwarfare.podbean.com/) [<i class="bi bi-rss"></i>](https://feed.podbean.com/IrregularWarfare/feed.xml)
- [West Point Association of Graduates](https://www.westpointaog.org/news/news-room/?podcast=on&search-form-media-types-hidden-input=podcast) [<i class="bi bi-rss"></i>](https://feeds.simplecast.com/bFcXpdg_)
- [WashingtonWise](https://www.schwab.com/learn/washingtonwise) [<i class="bi bi-rss"></i>](https://feeds.schwab.com/washingtonwise)
- [TED Talks Daily](https://www.ted.com/talks) [<i class="bi bi-rss"></i>](https://feeds.feedburner.com/TEDTalks_audio) [<i class="bi bi-film"></i>](https://feeds.feedburner.com/TedtalksHD)
- [NPR News Now](https://www.npr.org/podcasts/500005/npr-news-now) [<i class="bi bi-rss"></i>](https://feeds.npr.org/500005/podcast.xml)
- [The World in Brief from The Economist](https://shows.acast.com/theeconomistmorningbriefing/) [<i class="bi bi-rss"></i>](https://feeds.acast.com/public/shows/theeconomistmorningbriefing)
- [Up First from NPR](https://www.npr.org/podcasts/510318/up-first) [<i class="bi bi-rss"></i>](https://feeds.npr.org/510318/podcast.xml)
