---
title: "Sonny Bhatia"
about:
  id: headline
  template: trestles
  image: https://gravatar.com/avatar/d3a9cc1b103d1d983c1cf41bad7b6587e5efd5a2525866b9fce14dcb5f949fcf?size=360
  image-shape: round
  image-width: 15em
  links:
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/aadityabhatia/
    - icon: github
      text: Github
      href: https://github.com/aadityabhatia
    - icon: person-badge
      text: ORCID
      href: https://orcid.org/0000-0001-9953-8684
format:
  html:
    toc: false
---

::: {#headline}

Instructor, [EECS](https://www.westpoint.edu/academics/departments/electrical-engineering-and-computer-science), [US Military Academy at West Point](https://www.westpoint.edu/)


### Teaching

[CY350: Computer Networks](https://cy350.bhatia.dev/){.btn .btn-primary .disabled}

[CS380: Computer Systems and Organization](https://cs380.bhatia.dev/){.btn .btn-primary .disabled}


### More

[Awesome Articles and Resources](/awesome.qmd){.btn .btn-primary}

[ArgMap: MS Thesis Project](https://argmap.bhatia.dev/){.btn .btn-primary}

:::

<div style="margin-top: 3em;"></div>


## Ideas

- [ArgMap: How can LLMs enable us to ingest massive streams of unstructured information, incorporate diverse perspectives and distill them into actionable insights that align with public opinion?](https://argmap.bhatia.dev/). [Bowling Green, KY ran a study](https://polygraph-cool.github.io/m2-report/) (2025) using [pol.is](https://pol.is/) for deliberation at scale.

- How do we leverage AI to best develop critical thinking skills in the classroom? How do we protect against AI taking over? [Lodestone](https://maggieappleton.com/lodestone/) is a great thought experiment in this space.

- [AutoGrader: How can LLMs assess student homework and provide meaningful feedback?](https://github.com/aadityabhatia/autograder)

- What design patterns can enable us to collaborate with other humans and AI agents to collectively solve [wicked problems](https://en.m.wikipedia.org/wiki/Wicked_problem)? How do we leverage machines to act as [complementary](https://nautil.us/will-ai-harm-us-better-to-ask-how-well-reckon-with-our-hybrid-nature-236098/) [cognitive artifacts](https://doi.org/10.1007/BF02032391) that augment our human capabilities?


## Publications

- [Moderating Democratic Discourse with LLMs](https://link.springer.com/chapter/10.1007/978-3-031-72241-7_12), SBP-BRiMS (September 2024)

- [Using LLMs to Structure and Visualize Policy Discourse](https://doi.org/10.1007/978-981-97-9536-9_5), [DemocrAI workshop at IJCAI 2024](https://sites.google.com/view/democrai2024) (August 2024) [Best Paper Award]{.btn .btn-success .disabled}

- [Advancing Policy Insights: Opinion Data Analysis and Discourse Structuring Using LLMs](https://stars.library.ucf.edu/etd2023/204/). Graduate Thesis and Dissertation 2023-2024. University of Central Florida. (May 2024) [UCF Founders' Day Outstanding Master's Thesis Award]{.btn .btn-success .disabled}

- [Generally Genius: A Generals.io Agent Development and Data Collection Framework](https://ojs.aaai.org/index.php/AIIDE/article/view/27536). Proceedings of the AAAI Conference on Artificial Intelligence and Interactive Digital Entertainment (October 2023)


## Past Courses

### Spring 2025
[CY305: Cyber Foundations]{.btn .btn-secondary .disabled}

### Fall 2024
[CY105: Computing Fundamentals](https://cy105.bhatia.dev/){.btn .btn-primary}
